kind: Pod
apiVersion: v1
metadata:
  name: devpod
spec:
  containers:
  - image: moander/devpod
    imagePullPolicy: Always
    name: devpod
  restartPolicy: Always
  terminationGracePeriodSeconds: 1


